export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Footer } from './Footer/Footer'
export { default as Service } from './Service/Service'
export { default as Testimonial } from './Testimonial/Testimonial'
export { default as Showcase } from './Showcase/Showcase'
